// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import Script from "next/script";
import "./globals.css";

export const metadata: Metadata = {
  title: "FutBase - Super-app do Futebol de Base",
  description: "Matchmaking de amistosos, arbitragem e mídia integrada para o futebol de base brasileiro",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body className="font-geist-sans antialiased">
        {children}
      </body>
    </html>
  );
}